// <auto-generated />
namespace AWEARNESS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class subscriberaddon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(subscriberaddon));
        
        string IMigrationMetadata.Id
        {
            get { return "201510190155365_subscriber addon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
